### ISSUE TITLE
Extend beyond README.md

### ISSUE THREAD

**Issue by dim** [dave/rebecca#2]
It would be nice to be able to specify either a filename or a glob to apply becca to more than just the README. I would like to e.g. use it to generate the `doc.go.tpl`.

**Comment by dave** [comment]
Hey Dimitrij, 

I'm pretty busy on other projects now. I think if I was going to work on this project again I'd re-write to migrate from using templates to a non-destructive generation process, hiding the tags in markdown comments - based on the work in https://github.com/campoy/embedmd - either that or I'd trash this project and just send Francesc a PR for embedmd to more easily extract doc / examples.

However ... since this is a relatively small addition, I'll happily consider a PR adding a flag to specify the filename.

**Comment by dave** [comment]
Fixed by https://github.com/dave/rebecca/pull/3
